# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseAuthSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  # Pods for Google login
  pod 'GoogleSignIn'
  
  # Pods for Facebook login
  pod 'FBSDKLoginKit'
  
end
